//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
<<<<<<< HEAD
// Generated on: 2021.03.23 at 06:19:08 PM GMT 
=======
// Generated on: 2021.03.22 at 02:51:01 PM GMT 
>>>>>>> configure-ci-cd
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.turntabl.io/producer/clientOrders", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package io.turntabl.producer.clientOrders;
